### ISSUE TITLE
Doesn't working properly on Heroku

### ISSUE THREAD

**Issue by matheuschimelli** [playwright-community/heroku-playwright-buildpack#17]
First I would like to thank you for this buildback. 

I would like to report a bug that i found when i was trying to deploy the `heroku-playwright-buildback`.
Some important infos:

- Node v17.6.0
- Npm v8.5.1
- Running on Heroku
I'm using Typescript as well.

What's happening is that when i deploy heroku-playwright-buildback it doensn't work. However when i use the puppeteer buildpack `https://github.com/jontewks/puppeteer-heroku-buildpack.git` my app works.

I'm suspecting there is a bug but I don't know where it is.

```typescript
browserType.launch: Executable doesn't exist at /app/node_modules/playwright-chromium/node_modules/playwright-core/.local-browsers/chromium-973391/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at playwrightCrawler (/app/dist/lib/crawler-base.js:12:58)
    at default_1 (/app/dist/jobs/crawlers/crawler-tjpr-diary/sandbox.js:11:97)
    at processor (/app/node_modules/bull/lib/process/master.js:69:50)
    at /app/node_modules/bull/lib/process/master.js:91:33
    at process.<anonymous> (/app/node_modules/bull/lib/process/master.js:109:9)
    at processEmit [as emit] (/app/node_modules/signal-exit/index.js:175:34)
```

**Comment by bauerjon** [comment]
Same issue here. @matheuschimelli are you using yarn? i found that [the demo](https://github.com/playwright-community/heroku-playwright-example) broke when using yarn as that is what we are trying to get to work on our end.

@mxschmitt any thoughts on how to get the demo/buildpack to work with yarn?

**Comment by matheuschimelli** [comment]
> Same issue here. @matheuschimelli are you using yarn? i found that [the demo](https://github.com/playwright-community/heroku-playwright-example) broke when using yarn as that is what we are trying to get to work on our end.
> 
> @mxschmitt any thoughts on how to get the demo/buildpack to work with yarn?

Yes. I'm using Yarn. However, i also tried with npm and i got that error.

**Comment by bauerjon** [comment]
@matheuschimelli I found that it wasn't related to yarn but the newer version of  "playwright-chromium".

try hardcoding your package.json value for  "playwright-chromium" or similar to  `1.15.0`. the newer versions seem to have a dependency called "playwright-core" which don't seem to play nicely with the build pack as far as I can tell

**Comment by matheuschimelli** [comment]
> @matheuschimelli I found that it wasn't related to yarn but the newer version of "playwright-chromium" (or similar).
> 
> try hardcoding your package.json value for "playwright-chromium" or similar to `1.15.0`. the newer versions seem to have a dependency called "playwright-core" which don't seem to play nicely with the build pack as far as I can tell

Interesting. Thanks for the tip. 

I'm using `https://github.com/jontewks/puppeteer-heroku-buildpack.git` with playwright and it works like a charm as well.

**Comment by ZeroByter** [comment]
Hey guys, so was very frustated at this problem as I had it too, am using Yarn.
I followed your advice, downgraded to 1.15.0 and it works, thanks.
Hopefully a proper fix can be found some time.

**Comment by matheuschimelli** [comment]
> Hey guys, so was very frustated at this problem as I had it too, am using Yarn. I followed your advice, downgraded to 1.15.0 and it works, thanks. Hopefully a proper fix can be found some time.

Yes this is sad! But i have hope that one day everything will be better and all of us that are facing issues will have everlast happiness.

**Comment by amy-mac** [comment]
This just bit us after we upgraded our `playwright-chromium` package from 1.13 to 1.21. Glad this thread was here to point the way and hope this gets fixed soon.

**Comment by hbtalha** [comment]
Is there any way to make this work using playwright-python??

**Comment by zibdie** [comment]
Hi, trying to bring this issue back to light.

Using the Python version of Playwright and it seems to compile successfully
[heroku_log.txt](https://github.com/playwright-community/heroku-playwright-buildpack/files/9128702/heroku_log.txt)

But getting this in the logs
```
2022-07-17T22:52:42.235763+00:00 app[web.1]:   File "/app/downloader.py", line 33, in scrapePage

2022-07-17T22:52:42.235763+00:00 app[web.1]:     browser = await p.chromium.launch(

2022-07-17T22:52:42.235763+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 11399, in launch

2022-07-17T22:52:42.235764+00:00 app[web.1]:     await self._impl_obj.launch(

2022-07-17T22:52:42.235764+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 93, in launch

2022-07-17T22:52:42.235766+00:00 app[web.1]:     Browser, from_channel(await self._channel.send("launch", params))

2022-07-17T22:52:42.235766+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send

2022-07-17T22:52:42.235767+00:00 app[web.1]:     return await self._connection.wrap_api_call(

2022-07-17T22:52:42.235767+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 370, in _

2022-07-17T22:52:42.235767+00:00 app[web.1]:     return await result

2022-07-17T22:52:42.235768+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send

2022-07-17T22:52:42.235768+00:00 app[web.1]:     result = next(iter(done)).result()

2022-07-17T22:52:42.235769+00:00 app[web.1]: playwright._impl._api_types.Error: Executable doesn't exist at /app/.heroku/python/lib/python3.10/site-packages/playwright/driver/package/.local-browsers/chromium-1012/chrome-linux/chrome

2022-07-17T22:52:42.235769+00:00 app[web.1]: ╔════════════════════════════════════════════════════════════╗

2022-07-17T22:52:42.235770+00:00 app[web.1]: ║ Looks like Playwright was just installed or updated.       ║

2022-07-17T22:52:42.235770+00:00 app[web.1]: ║ Please run the following command to download new browsers: ║

2022-07-17T22:52:42.235771+00:00 app[web.1]: ║                                                            ║

2022-07-17T22:52:42.235771+00:00 app[web.1]: ║     playwright install                                     ║

2022-07-17T22:52:42.235771+00:00 app[web.1]: ║                                                            ║

2022-07-17T22:52:42.235772+00:00 app[web.1]: ║ <3 Playwright Team                                         ║

2022-07-17T22:52:42.235772+00:00 app[web.1]: ╚════════════════════════════════════════════════════════════╝

```

**Comment by rikusen0335** [comment]
Not advertising just let you know, I found a solution see this:
https://dev.to/rikus3n/deploy-playwright-on-heroku-2c90
